// TCG Companion — Official Kontrola Asset Resolver
// Resolves authentic high-res cards from public/Kontrolla_Data/Graphics

export const getBaseUrl = () => {
  const base = import.meta.env?.BASE_URL || '/';
  return base.endsWith('/') ? base : `${base}/`;
};

// Map of Action Card names to file paths relative to Kontrolla_Data/Graphics
const ACTION_CARD_IMAGE_MAP = {
  // BASIC ACTION CARDS
  'ABANDON': 'ACTION CARDS/BASIC/ABANDON CARD.png',
  'ANTIDOTE FULL': 'ACTION CARDS/BASIC/ANTIDOTE FULL CARD.png',
  'ANTIDOTE X1': 'ACTION CARDS/BASIC/ANTIDOTE X1 CARD.png',
  'ANTIDOTE X2': 'ACTION CARDS/BASIC/ANTIDOTE X2 CARD.png',
  'ATTACK X1': 'ACTION CARDS/BASIC/ATTACK X1 CARD.png',
  'ATTACK X2': 'ACTION CARDS/BASIC/ATTACK X2 CARD.png',
  'BOOMERANG FULL': 'ACTION CARDS/BASIC/BOOMERANG CARD.png',
  'DEFENCE - BASIC': 'ACTION CARDS/BASIC/DEFENCE BASIC CARD.png',
  'DEFENCE - COUNTER': 'ACTION CARDS/BASIC/DEFENCE COUNTER CARD.png',
  'DODGE - BASIC': 'ACTION CARDS/BASIC/DODGE BASIC CARD.png',
  'FIRE FLAME X1': 'ACTION CARDS/BASIC/FIRE FLAME X1 CARD.png',
  'FREEZE X1': 'ACTION CARDS/BASIC/FREEZE X1 CARD.png',
  'HEAL H10': 'ACTION CARDS/BASIC/HEAL H10 CARD.png',
  'HEAL H20': 'ACTION CARDS/BASIC/HEAL H20 CARD.png',
  'HEAL CLEANSE+RESTORE': 'ACTION CARDS/PREMIUM/HEAL CLEANSE + RESTORE CARD.png',
  'HEAL CLEAN + RESTORE': 'ACTION CARDS/PREMIUM/HEAL CLEANSE + RESTORE CARD.png',
  'HEAL CLEANSE + RESTORE': 'ACTION CARDS/PREMIUM/HEAL CLEANSE + RESTORE CARD.png',
  'LIGHTNING X1': 'ACTION CARDS/BASIC/LIGHTNING X1 CARD.png',
  'LIGHTNING X2': 'ACTION CARDS/BASIC/LIGHTNING X2 CARD.png',
  'MISDIRECT': 'ACTION CARDS/BASIC/MISDIRECT BASIC CARDS.png',
  'POISON X1': 'ACTION CARDS/BASIC/POISON X1 CARD.png',
  'POISON X2': 'ACTION CARDS/BASIC/POISON X2 CARD.png',
  'RETREAT': 'ACTION CARDS/BASIC/RETREAT BASIC CARD.png',
  'REVIVE': 'ACTION CARDS/BASIC/REVIVE CARD.png',
  'SHIELD BASIC +25 HP': 'ACTION CARDS/BASIC/SHIELD BASIC +25HP CARD.png',
  'SLEEPY X1': 'ACTION CARDS/BASIC/SLEEPY X1 CARD.png',
  'SOUL ALLIANCE': 'ACTION CARDS/BASIC/SOUL ALLIANCE CARD.png',
  'STABILITY CRYSTAL': 'ACTION CARDS/BASIC/STABILITY CRYSTAL CARD.png',
  'TIME MACHINE': 'ACTION CARDS/BASIC/TIME MACHINE CARD.png',
  'VISION X1': 'ACTION CARDS/BASIC/VISION X1 CARD.png',
  'VITALITY GAIN V10': 'ACTION CARDS/BASIC/VITALITY GAIN V20 CARD.png',
  'VITALITY GAIN V20': 'ACTION CARDS/BASIC/VITALITY GAIN V20 CARD.png',
  'X-CHANGE X1': 'ACTION CARDS/BASIC/XCHANGE X1 CARD.png',
  'ZOMBIE MODE': 'ACTION CARDS/BASIC/ZOMBIE MODE CARD.png',

  // PREMIUM ACTION CARDS
  '+DEFENCE D5': 'ACTION CARDS/PREMIUM/+DEFENCE D5 CARD.png',
  '+DEFENCE D10': 'ACTION CARDS/PREMIUM/+DEFENCE D10 CARD.png',
  '+DEFENCE D15': 'ACTION CARDS/PREMIUM/+DEFENCE D15 CARD.png',
  '+DEFENCE D20': 'ACTION CARDS/PREMIUM/+DEFENCE D20 CARD.png',
  'BACK STAB': 'ACTION CARDS/PREMIUM/BACK STAB CARD.png',
  'DEFENCE FULL GUARD': 'ACTION CARDS/PREMIUM/DEFENCE FULL GUARD CARD.png',
  'DODGE - COUNTER': 'ACTION CARDS/PREMIUM/DODGE COUNTER CARD.png',
  'DRAIN': 'ACTION CARDS/PREMIUM/DRAIN CARD.png',
  'FIRE FLAME INFERNO LOCK': 'ACTION CARDS/PREMIUM/FIRE FLAME INFERNO LOCK.png',
  'FIRE FLAME X2': 'ACTION CARDS/PREMIUM/FIRE FLAME X2 CARD.png',
  'FREEZE X2': 'ACTION CARDS/PREMIUM/FREEZE X2 CARD.png',
  'HEAL H30': 'ACTION CARDS/PREMIUM/HEAL H30 CARD.png',
  'HEAL H40': 'ACTION CARDS/PREMIUM/HEAL H40 CARD.png',
  'SHIELD ADVANCE +100HP': 'ACTION CARDS/PREMIUM/SHIELD ADVANCE +100HP CARD.png',
  'SHIELD FIRE + 50HP': 'ACTION CARDS/PREMIUM/SHIELD FIRE +50HP.png',
  'SHIELD FIRE +50HP': 'ACTION CARDS/PREMIUM/SHIELD FIRE +50HP.png',
  'SHIELD SACRED PROTECTION': 'ACTION CARDS/PREMIUM/SHIELD SACRED PROTECTION CARD.png',
  'SLEEPY X2': 'ACTION CARDS/PREMIUM/SLEEPY X2 CARD.png',
  'VAMPIRE LIFE STEAL': 'ACTION CARDS/PREMIUM/VAMPIRE LIFE STEAL CARD.png',
  'VISION FULL': 'ACTION CARDS/PREMIUM/VISION FULL CARD.png',
  'VITALITY GAIN V30': 'ACTION CARDS/PREMIUM/VITALITY GAIN V30 CARD.png',
  'VITALITY V40': 'ACTION CARDS/PREMIUM/VITALITY V40 CARD.png',
  'X-CHANGE FULL': 'ACTION CARDS/PREMIUM/XCHANGE FULL CARD.png'
};

// BLITZ CARDS by character key
const BLITZ_CARD_MAP = {
  'bee': 'BLITZ CARDS/BEE BLITZ GOLD.png',
  'chyna': 'BLITZ CARDS/CHYNA BLITZ GOLD.png',
  'katsumi': 'BLITZ CARDS/KAT BLITZ GOLD.png',
  'kiko': 'BLITZ CARDS/KIKO BLITZ GOLD.png',
  'poochi': 'BLITZ CARDS/POOCHI BLITZ GOLD.png',
  'queeny': 'BLITZ CARDS/QUEENY BLITZ GOLD.png',
  'shroomy': 'BLITZ CARDS/SHROOMY BLITZ GOLD.png'
};

// KONTROL CARDS by character key
const KONTROL_CARD_MAP = {
  'bee': 'KONTROL CARDS/BEE KONTROL GOLD.png',
  'chyna': 'KONTROL CARDS/CHYNA KONTROL GOLD.png',
  'katsumi': 'KONTROL CARDS/KAT KONTROL GOLD.png',
  'kiko': 'KONTROL CARDS/KIKO KONTROL GOLD.png',
  'poochi': 'KONTROL CARDS/POOCHI KONTROL GOLD.png',
  'queeny': 'KONTROL CARDS/QUEENY KONTROL GOLD.png',
  'shroomy': 'KONTROL CARDS/SHROOMY KONTROL GOLD.png'
};

// REGULAR CHARACTER ATTACK CARDS
const REGULAR_ATTACK_CARD_MAP = {
  // Chynaman
  'FIRE OF FURY PER PUNCH': 'REGULAR CARDS/CHYNA FOF GOLD.png',
  'FIRE TIGER SOUL PUNCH': 'REGULAR CARDS/CHYNA FTSP GOLD.png',
  'GOLDEN MIC LIGHTING': 'REGULAR CARDS/CHYNA GML GOLD.png',

  // Bee
  'STING SLAP PER STING': 'REGULAR CARDS/BEE SPPS.png',
  'PAPARAZZI STUN': 'REGULAR CARDS/BEE PAP STUN.png',
  'BEE DRONE BOMB': 'REGULAR CARDS/BEE BDB.png',

  // Kiko
  'TAIL WHIP PER WHIP': 'REGULAR CARDS/KIKO TWPW GOLD.png',
  'MULTIPLICITY': 'REGULAR CARDS/KIKO MULTI GOLD.png',
  'SOUL BLAST 3000': 'REGULAR CARDS/KIKO SB3000.png',

  // Katsumi
  'SAVAGE PAWS PER STRIKE': 'REGULAR CARDS/KAT SPPS GOLD.png',
  'SHADOW PURR': 'REGULAR CARDS/KAT SHADOW PURR.png',
  'CLAW OF FATE': 'REGULAR CARDS/KAT COF.png',

  // Poochi
  'GLITTER SPARKS PER SPARK': 'REGULAR CARDS/POOCHI GSPS.png',
  'LASSO OF TRUTH': 'REGULAR CARDS/POOCHI LOT.png',
  'GLITTER BURST': 'REGULAR CARDS/POOCHI GB.png',

  // Queeny
  'HAIR WHIP PER WHIP': 'REGULAR CARDS/QUEENY HWPW.png',
  'SIREN BLAST': 'REGULAR CARDS/QUEENY SB.png',
  'RAINBOW FAN BLAST': 'REGULAR CARDS/QUEENY RFB.png',

  // Shroomy
  'POPPERS PER POP': 'REGULAR CARDS/SHROOMY PPP.png',
  'MS BOMBA': 'REGULAR CARDS/SHROOMY MS B.png',
  'SOUL SNATCHER': 'REGULAR CARDS/SHROOMY SOUL SNATCHER.png'
};

// WILD CARDS
const WILD_CARD_MAP = {
  'chyna': 'WILD CARDS/CHYNA WILD CARD REG.png',
  'bee': 'WILD CARDS/BEE WILD CARD GOLD.png',
  'katsumi': 'WILD CARDS/KAT WILD CARD GOLD.png',
  'kiko': 'WILD CARDS/KIKO WILD CARD GOLD.png',
  'poochi': 'WILD CARDS/POOCHI WILD CARD GOLD.png',
  'queeny': 'WILD CARDS/QUEENY WILD CARD GOLD.png',
  'shroomy': 'WILD CARDS/SHROOMY WILD CARD GOLD.png',
  'sue': 'WILD CARDS/SUE ELLEN_S WILD CARD GOLD.png'
};

export const getCardGraphicUrl = (cardName, characterId = null) => {
  if (!cardName) return '';
  const cleanName = cardName.trim().toUpperCase();

  // Check if it's Blitz
  if (cleanName.includes('BLITZ') || cleanName.includes('SAIGO')) {
    const blitzPath = BLITZ_CARD_MAP[characterId?.toLowerCase()] || BLITZ_CARD_MAP.chyna;
    return encodeURI(`${getBaseUrl()}Kontrolla_Data/Graphics/${blitzPath}`);
  }

  // Check if it's Kontrol
  if (cleanName.includes('KONTROL')) {
    const kontrolPath = KONTROL_CARD_MAP[characterId?.toLowerCase()] || KONTROL_CARD_MAP.chyna;
    return encodeURI(`${getBaseUrl()}Kontrolla_Data/Graphics/${kontrolPath}`);
  }

  // Check direct Action Card Map
  if (ACTION_CARD_IMAGE_MAP[cleanName]) {
    return encodeURI(`${getBaseUrl()}Kontrolla_Data/Graphics/${ACTION_CARD_IMAGE_MAP[cleanName]}`);
  }

  // Check if it's a character combat move
  if (REGULAR_ATTACK_CARD_MAP[cleanName]) {
    return encodeURI(`${getBaseUrl()}Kontrolla_Data/Graphics/${REGULAR_ATTACK_CARD_MAP[cleanName]}`);
  }

  // Fallback to basic attack card
  return encodeURI(`${getBaseUrl()}Kontrolla_Data/Graphics/ACTION CARDS/BASIC/ATTACK X1 CARD.png`);
};

export const getCharacterAttackGraphicUrl = (attackName) => {
  if (!attackName) return '';
  const cleanName = attackName.trim().toUpperCase();
  const rel = REGULAR_ATTACK_CARD_MAP[cleanName];
  if (rel) {
    return encodeURI(`${getBaseUrl()}Kontrolla_Data/Graphics/${rel}`);
  }
  return encodeURI(`${getBaseUrl()}Kontrolla_Data/Graphics/ACTION CARDS/BASIC/ATTACK X1 CARD.png`);
};

export const getWildCardGraphicUrl = (characterId) => {
  const rel = WILD_CARD_MAP[characterId?.toLowerCase()] || WILD_CARD_MAP.chyna;
  return encodeURI(`${getBaseUrl()}Kontrolla_Data/Graphics/${rel}`);
};
