export const presetQuestions = [
  "What is the story behind Attention TCG?",
  "Who is the main villain?",
  "How many Stability Crystals are needed to win?",
  "What is an Action Card?",
  "What is a Character Card?",
  "How do players decide who goes first?",
  "How many Action Cards does a player start with?",
  "How many Character Cards does a player start with?",
  "What are Energy Tokens?",
  "How much energy is a Black Token worth?",
  "How much energy is a Red Token worth?",
  "How much energy is a Gold Token worth?",
  "Can I trade Energy Tokens with another player?",
  "What does HP stand for?",
  "What happens when HP reaches 0?",
  "What does AP stand for?",
  "What does DP stand for?",
  "What are Retreat Points (RP)?",
  "How does retreating work?",
  "What happens if you hit a character's weakness?",
  "What is Katsumi's weakness?",
  "What is Zabina Bee Sole's weakness?",
  "What is Chynaman's weakness?",
  "What is Kiko the Monkey's weakness?",
  "What is Poochi's weakness?",
  "What is Queeny's weakness?",
  "What is Shroomy's weakness?",
  "What is a Chance Card?",
  "How do you level up?",
  "At what HP can you use Level 2 cards?",
  "What is a Status Effect?",
  "What does Cooldown mean?",
  "What is a Critical Hit?",
  "What is a Combo?",
  "How does a Counter work?",
  "What does Redirect mean?",
  "How does healing work in the game?",
  "What is the Kontrol Card?",
  "How does Mind Strength affect the Kontrol Card?",
  "Can you use the Kontrol Card to steal Action Cards?",
  "What is Katsumi's Mind Strength?",
  "What is Zabina's Mind Strength?",
  "What is Chynaman's Mind Strength?",
  "What is Kiko's Mind Strength?",
  "What is Poochi's Mind Strength?",
  "What is Queeny's Mind Strength?",
  "What is Shroomy's Mind Strength?",
  "What happens if a Chance Card is used against Kontrol?",
  "How many Kontrol Cards can be used per match?",
  "What is the cooldown period for Kontrol?",
  "What is the Blitz Card?",
  "When can you use the Blitz Card?",
  "How much HP do you lose when using Blitz?",
  "What is the AP of a successful Saigo No Blitz?",
  "How does a One vs One Attack work?",
  "How does a One vs All Attack work?",
  "How is damage divided in One vs All Attack?",
  "What happens if the main attack of Blitz misses?",
  "How many Blitz Cards can be used per match?",
  "What is Chynaman's Fire of Fury attack?",
  "What is Chynaman's Fire Tiger Soul Punch?",
  "What is Chynaman's Golden Mic Lighting?",
  "What is a Wild Card?",
  "How does individual defense without a Defense Card work?",
  "What is Kiko's Tail Whip attack?",
  "What is Kiko's Multiplicity attack?",
  "What is Kiko's Soul Blast 3000?",
  "What is Shroomy's Poppers attack?",
  "What is Shroomy's MS Bomba attack?",
  "What is Shroomy's Soul Snatcher attack?",
  "What is Zabina's Sting Slap attack?",
  "What happens on a successful Paparazzi Stun?",
  "What is Zabina's Bee Drone Bomb?",
  "What is Katsumi's Savage Paws attack?",
  "What is Katsumi's Shadow Purr?",
  "What is Katsumi's Claw of Fate?",
  "What is Poochi's Glitter Sparks attack?",
  "What happens on a successful Lasso of Truth?",
  "What is Poochi's Glitter Burst attack?",
  "What is Queeny's Hair Whip attack?",
  "What is Queeny's Siren Blast?",
  "What is Queeny's Rainbow Fan Blast?",
  "What is the Amplify Bonus Card?",
  "Does the Amplify Card require a dice roll?",
  "What does TCG stand for?",
  "Can you stack cards?",
  "What is a passive ability?",
  "What is an active ability?",
  "What is a Turn?",
  "What is a Round?",
  "How many Energy Tokens are needed for a regular attack?",
  "How many Energy Tokens for a super attack?",
  "How many Energy Tokens for Kontrol?",
  "How many Energy Tokens for Blitz?",
  "How do players decide the turn order?",
  "Can two players choose the same character?",
  "Do players show their Action and Character cards?",
  "Can you win with only two Stability Crystals in a 1v1?",
  "How many Energy Tokens do you get per turn?",
  "Can you ask for your Energy Token after your turn?",
  "Can the game be cast to a TV?",
  "Is there a local social play feature?",
  "What is the difference between clarifying and compact mode?",
  "Can the chatbot invent rules?",
  "Does the scoreboard update instantly?",
  "How are scores updated for Poison and Antidote cards?",
  "Who is the Host Player?",
  "How to use an Attack card?",
  "How to use a Shield card?",
  "Can you undo an action if you make a mistake?"
];
