export const presetQuestions = [
  "What is the story of this game?",
  "Where is the story and characters based on?",
  "How do you decide which player starts first?",
  "How do you begin the game?",
  "How many Actions Cards do you pass out and have in hand at all times?",
  "Do I show players my Action Cards?",
  "How many Character Cards do you pass out and have in hand at all times?",
  "Can I choose which Character Cards I want to use?",
  "How many Character Cards can you have in your Character Card deck?",
  "Can more than one player be the same character?",
  "What does the Asian symbol 注意 mean?",
  "What does the Asian symbol 英雄 (eiyuu) in the upper left hand corner on a Character card stand for?",
  "What does #AMD or #AMDUniverse stands for?",
  "What is the maximum number of players for this game?",
  "What is the minimum number of players for this game?",
  "How many stability energy crystal cards do each player start out with?",
  "If there are only two players how many stability energy crystal cards do each player receive?",
  "How do a player receive a stability energy crystal?",
  "How do I win this game?",
  "What is Character Weakness?",
  "Why are there some Character Cards with different weaknesses?",
  "What is HP?",
  "How do I lose in this game?",
  "What is AP?",
  "What is DP?",
  "What is Retreat?",
  "Do I need a Retreat Action Card to do this move?",
  "How does Retreat work?",
  "Do I have to roll a dice to determine whether the Character can retreat?",
  "How many dice do I need to use to determine whether the Character can retreat?",
  "What does the numbers next to the Retreat text mean?",
  "What happens if a player does not roll the necessary number to Retreat?",
  "What happens if I roll doubles?",
  "Do I roll two dice on Character Card/Attack?",
  "When do I roll only one dice?",
  "How do I activate a Character’s basic defense?",
  "Do I have to roll the dice to activate the Poison card?",
  "Do I have to roll the dice to activate the Lightning card?",
  "Do I have to roll the dice to activate the Fire Flame card?",
  "Do I have to roll the dice to activate a shield?",
  "What are Energy Tokens?",
  "What color is 1 ET?",
  "What color is 2 ET?",
  "What color is 3 ET?",
  "How many energy tokens do each player start out in the game?",
  "Does a player receive an extra energy token after the game begins?",
  "Can I claim my energy token after my turn is over?",
  "Do I need Energy Tokens if I am defending?",
  "How many Energy Tokens do I need to perform a Basic Attack?",
  "How many Energy Tokens do I need to perform a Super Attack?",
  "How many Energy Tokens do I need to perform a Kontrol Attack?",
  "How many Energy Tokens do I need to perform a Blitz Attack?",
  "What are Action Cards?",
  "Does a Fire Shield lose HP when attacked by a Fire Attack?",
  "Do I have to roll to activate a Shield Card?",
  "Can I use the Abandon card to avoid an attack or defense?",
  "What are Character Cards?",
  "Can I play the game with just Character Cards?",
  "What do the Gem colors in the upper right hand corner of a Character mean?",
  "How often can I use my Kontrol Card?",
  "Is a Kontrol Card considered a rare card?",
  "How to attack?",
  "How is damage dealt in One vs. All Attack?",
  "Can I defend a No Saigo Blitz attack?",
  "How many times can I use a Blitz attack?",
  "Can a player roll the dice to determine whether an opponent has control over them?",
  "What are Fate Cards?",
  "Can I choose which Fate Card I get?",
  "Do I have to use my Fate Card immediately?",
  "In “Steal Your Fate” do I need to replace my Action Card that was taken by my opponent?",
  "In “Steal Your Fate” if I receive an extra Action Card from an opponent do I keep all my cards?",
  "Does a Heal Card remove a Poison Card?",
  "Can I use my Character Cards, moves, and attack when they are a Zombie?",
  "If a Zombie is successful in its attack, how will it affect the opponent?",
  "Can a Zombie infect another Zombie player?",
  "Can I win the game as a Zombie?",
  "If I am in Zombie Mode. Do I need a Revive Card to come back alive?",
  "How much HP does a Zombie receive when it dies?",
  "What are some of the benefits of being a Zombie?",
  "If a player does not have 5 Poison Cards will still be in Zombie Mode?",
  "Who can I inflict Poison on?",
  "If a player has 4 Poison Cards and is attacked by another player with a Kontrol Card. Can he or she use a Poison Card to become a zombie and avoid being controlled?",
  "Why is Poochi’s weakness similar to the human characters?",
  "Is Poochi, Kiko the Monkey’s girl?",
  "Is Queeny human?",
  "Why is fire Queeny’s weakness?",
  "What are Poison Cards?",
  "Do I have to roll dice to activate a Poison Card?",
  "What is the maximum number of Poison Cards a player can have?",
  "Can I use a Poison Card on myself?"
];
